In [ ]:
1 . Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.


In [1]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)
print(arr.shape)

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr12)
print(arr12.ndim)
print(arr12.shape)


arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[1 2 3 4 5]
1
(5,)
[[1 2 3]
 [4 5 6]]
2
(2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3
(2, 2, 3)


2 . Create:
an array of zeros of shape (3,3)


an array of ones of shape (2,5)


an array filled with 7

In [8]:
arr = np.zeros((3,3))
print(arr)

arr1 = np.ones((2,5))
print(arr1)

arr2 = np.full((3,3),7)
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


3 . Create an array of even numbers between 10 and 50 using arange.

In [10]:
arr = np.arange(10,50,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


4 . Create a 4×4 matrix from 0–15. Then , extract:
the first row


the last column


a 2×2 subarray from the center

In [17]:
arr = np.arange(16).reshape(4, 4)
print(arr)
row = arr[0]
print(row)

column = arr[:, -1]
print(column)

subarray = arr[1:3, 1:3]
print(subarray)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[0 1 2 3]
[ 3  7 11 15]
[[ 5  6]
 [ 9 10]]
